const MISO_CONFIG = {
  name: "Miso",
  breed: "Nova Scotia Duck Tolling Retriever",
  birthday: "2026-03-10",

  // Adjust when you weigh him
  weightKg: 5.5,

  kibble: {
    brand: "Purina Pro Plan",
    product: "Puppy Medium — Chicken",
    expectedAdultWeightKg: 20, // Toller adult ~17–23 kg
    // Purina on-pack feeding table (g/day) by puppy age — adjust expectedAdultWeightKg if needed
    feedingTable: [
      { maxMonths: 3, min: 145, max: 265 },
      { maxMonths: 5, min: 320, max: 350 },
      { maxMonths: 8, min: 340, max: 355 },
      { maxMonths: 11, min: 300, max: 320 },
      { maxMonths: 12, min: 275, max: 275 },
    ],
  },

  // Meal times (24h) — edit to match your routine
  mealTimes: ["06:30", "12:30", "18:00"],

  // Transition to 2 meals when puppy is this many months old
  twoMealsFromMonths: 6,

  health: {
    vaccinations: [
      { dose: 1, label: "1st vaccination", date: null, done: true, note: "At breeder" },
      { dose: 2, label: "2nd vaccination · pick up Miso", date: "2026-05-26", done: false },
      { dose: 3, label: "3rd vaccination", date: "2026-06-18", done: false },
    ],
    deworming: [
      { dose: 1, label: "1st deworming tablets", date: null, done: true },
      { dose: 2, label: "2nd deworming tablets", date: "2026-05-28", done: false },
    ],
  },

  // Topics change by age — stages run until 18 months, then the last stage stays active
  topicStages: [
    {
      maxMonths: 4,
      label: "Early puppy",
      lead: "Settling in at home — socialisation window, vaccines, and building routines.",
      topics: [
        {
          id: "settling",
          title: "Settling in",
          icon: "🏠",
          priority: "high",
          summary: "First weeks at home — crate, sleep, and house training foundations.",
          items: ["Crate comfort & night routine", "House training progress", "Safe puppy-proof zones"],
        },
        {
          id: "social",
          title: "Socialisation",
          icon: "🐕",
          priority: "high",
          summary: "Critical window — positive first experiences with people, dogs, sounds, and surfaces.",
          items: ["New environments weekly", "Calm, friendly dogs only", "Handling paws, ears, mouth"],
        },
        {
          id: "health",
          title: "Health & vet",
          icon: "🩺",
          priority: "high",
          summary: "Puppy vaccinations, deworming, and first vet relationship.",
          items: ["Vaccination schedule", "Deworming dates", "Insurance & microchip"],
        },
        {
          id: "training",
          title: "Training basics",
          icon: "🎓",
          priority: "high",
          summary: "Bite inhibition, name response, and short positive sessions.",
          items: ["Sit & name response", "Bite inhibition", "Short sessions (2–5 min)"],
        },
        {
          id: "feeding",
          title: "Feeding & weight",
          icon: "🍽",
          priority: "medium",
          summary: "Pro Plan Puppy — 3 meals, weekly weigh-ins, watch body condition.",
          items: ["3 meals / day", "Weekly weigh-in", "Stool quality"],
        },
        {
          id: "sleep",
          title: "Sleep & routine",
          icon: "😴",
          priority: "medium",
          summary: "Puppies need 18–20 h sleep — enforce naps after play and meals.",
          items: ["18–20 h sleep/day", "Nap after every outing", "Quiet crate time"],
        },
        {
          id: "exercise",
          title: "Exercise",
          icon: "🏃",
          priority: "medium",
          summary: "Sniff walks only — no forced running or long hikes yet.",
          items: ["Sniff walks on soft ground", "~5 min/month rule (rough guide)", "No stairs or jumping"],
        },
        {
          id: "grooming",
          title: "Grooming",
          icon: "✂️",
          priority: "low",
          summary: "Introduce brushing and handling early so grooming stays easy.",
          items: ["Brush 2× per week", "Touch paws & ears daily", "Nail intro (file/clippers)"],
        },
      ],
    },
    {
      maxMonths: 6,
      label: "Teething & growth",
      lead: "Teething kicks in — chew management, leash skills, and growing confidence.",
      topics: [
        {
          id: "teething",
          title: "Teething",
          icon: "🦷",
          priority: "high",
          summary: "Peak chewing phase — redirect mouthing and protect furniture.",
          items: ["Frozen chew toys", "Redirect mouthing calmly", "Watch for retained baby teeth"],
        },
        {
          id: "social",
          title: "Socialisation",
          icon: "🐕",
          priority: "high",
          summary: "Keep exposing to new things — window is still open but narrowing.",
          items: ["New places & surfaces", "Different people & ages", "Traffic & city sounds (positive)"],
        },
        {
          id: "training",
          title: "Training",
          icon: "🎓",
          priority: "high",
          summary: "Build on basics — leash manners, stay, and recall on a long line.",
          items: ["Loose-leash walking", "Down & stay (short)", "Recall on long line"],
        },
        {
          id: "health",
          title: "Health & vet",
          icon: "🩺",
          priority: "high",
          summary: "Final puppy vaccines, flea/tick plan, and body condition checks.",
          items: ["Booster vaccinations", "Flea/tick prevention", "Body condition score"],
        },
        {
          id: "feeding",
          title: "Feeding & weight",
          icon: "🍽",
          priority: "medium",
          summary: "Amounts increase with growth — still on puppy food, watch waistline.",
          items: ["Adjust grams on bag", "Weekly weigh-in", "Ribs easy to feel"],
        },
        {
          id: "exercise",
          title: "Exercise",
          icon: "🏃",
          priority: "medium",
          summary: "Slightly longer sniff walks — still avoid repetitive jumping or hard running.",
          items: ["Longer sniff walks", "No jogging on pavement", "Swim intro (if warm & safe)"],
        },
        {
          id: "grooming",
          title: "Grooming",
          icon: "✂️",
          priority: "medium",
          summary: "Toller coat thickening — regular brushing prevents mats.",
          items: ["Brush 2–3× per week", "Nail trim every 2–3 weeks", "Ear checks after water"],
        },
        {
          id: "alone",
          title: "Alone time",
          icon: "🕐",
          priority: "low",
          summary: "Gradually build tolerance for being alone — prevents separation anxiety.",
          items: ["Short departures (5–15 min)", "Kong/chew when leaving", "No big fuss on return"],
        },
      ],
    },
    {
      maxMonths: 12,
      label: "Adolescent",
      lead: "Teen phase begins — recall may slip, energy rises, adult food transition ahead.",
      topics: [
        {
          id: "adolescent",
          title: "Adolescent behaviour",
          icon: "⚡",
          priority: "high",
          summary: "Expect testing boundaries — stay consistent and keep training fun.",
          items: ["Recall regression is normal", "Ignore attention-seeking", "Consistent rules at home"],
        },
        {
          id: "training",
          title: "Training",
          icon: "🎓",
          priority: "high",
          summary: "Proof skills with distractions — reliable recall is the top priority.",
          items: ["Recall with distractions", "Leave it & drop it", "Impulse control (wait at doors)"],
        },
        {
          id: "exercise",
          title: "Exercise",
          icon: "🏃",
          priority: "high",
          summary: "More activity now — retrieving, swimming, longer hikes on soft terrain.",
          items: ["Structured fetch sessions", "Swimming (Tollers love water)", "Avoid repetitive jumping"],
        },
        {
          id: "feeding",
          title: "Feeding transition",
          icon: "🍽",
          priority: "medium",
          summary: "Plan switch to adult food around 12 months — reduce to 2 meals.",
          items: ["Discuss adult food timing", "2 meals from ~6 months", "Monitor weight through growth spurt"],
        },
        {
          id: "health",
          title: "Health & vet",
          icon: "🩺",
          priority: "medium",
          summary: "Annual boosters, neuter discussion, and joint health awareness.",
          items: ["Annual vaccination plan", "Neuter timing (~12+ mo discuss)", "Hip/elbow awareness (breed)"],
        },
        {
          id: "grooming",
          title: "Grooming & coat",
          icon: "✂️",
          priority: "medium",
          summary: "Puppy coat changing to adult double coat — brush more during shedding.",
          items: ["Brush 3× per week in shed", "Undercoat rake when blowing coat", "Dental chews / brushing"],
        },
        {
          id: "social",
          title: "Social skills",
          icon: "🐕",
          priority: "low",
          summary: "Maintenance socialisation — focus on calm greetings and dog manners.",
          items: ["Calm greetings (4 on floor)", "Play with known dogs", "Café / pub visits (relaxed)"],
        },
      ],
    },
    {
      maxMonths: 18,
      label: "Young adult",
      lead: "Approaching maturity — solidify skills, adult routine, and breed-specific activities.",
      topics: [
        {
          id: "training",
          title: "Training & manners",
          icon: "🎓",
          priority: "high",
          summary: "Polish adult manners — reliable off-lead where safe, solid impulse control.",
          items: ["Off-lead recall (safe areas)", "Heel for busy areas", "Settle on mat in public"],
        },
        {
          id: "activity",
          title: "Breed activities",
          icon: "🎾",
          priority: "high",
          summary: "Tollers thrive on retrieving and mental work — channel that drive.",
          items: ["Retrieving games", "Scent work / nose games", "Consider agility foundations"],
        },
        {
          id: "health",
          title: "Health & vet",
          icon: "🩺",
          priority: "high",
          summary: "Adult health baseline — neuter done, annual check-ups, preventive care.",
          items: ["Annual health check", "Flea/tick & worming routine", "Weight at adult target (~17–23 kg)"],
        },
        {
          id: "feeding",
          title: "Adult feeding",
          icon: "🍽",
          priority: "medium",
          summary: "On adult food — adjust portions to maintain lean body condition.",
          items: ["Pro Plan Medium Adult", "2 meals / day", "Treats ≤ 10% of calories"],
        },
        {
          id: "exercise",
          title: "Exercise",
          icon: "🏃",
          priority: "medium",
          summary: "Full activity level — hikes, swim, fetch; joints still maturing until ~18 mo.",
          items: ["1–2 h activity / day", "Mix physical & mental", "Avoid heavy jump impact sports"],
        },
        {
          id: "grooming",
          title: "Grooming",
          icon: "✂️",
          priority: "medium",
          summary: "Adult coat care — seasonal shedding, nails, ears, teeth.",
          items: ["Brush 2–3× per week", "Seasonal undercoat blow", "Monthly nail & ear check"],
        },
        {
          id: "life",
          title: "Life & travel",
          icon: "✈️",
          priority: "low",
          summary: "Adult dog logistics — travel, boarding, and emergency prep.",
          items: ["Pet passport (if EU travel)", "Trusted boarding / sitter", "Emergency vet contact saved"],
        },
      ],
    },
  ],

  defaultChecklist: [
    "Pick up Miso — 2nd vaccination (Tue 26 May)",
    "2nd deworming tablets (Wed 28 May)",
    "Weigh Miso this week",
    "Brush coat",
    "Practice recall in garden",
  ],
};
